<?php

if (!defined('ABSPATH')) {
    exit;
}

final class FC_Admin
{
    public static function register_menu(): void
    {
        add_menu_page(
            'FiltroClientes',
            'FiltroClientes',
            'manage_options',
            'fc-dashboard',
            [self::class, 'render_dashboard_page'],
            'dashicons-chart-area',
            30
        );

        add_submenu_page('fc-dashboard', 'Dashboard', 'Dashboard', 'manage_options', 'fc-dashboard', [self::class, 'render_dashboard_page']);
        add_submenu_page('fc-dashboard', 'Conexion API', 'Conexion API', 'manage_options', 'fc-settings', [self::class, 'render_settings_page']);
        add_submenu_page(null, 'Ficha clinica', 'Ficha clinica', 'manage_options', 'fc-record', [self::class, 'render_record_page']);
    }

    public static function enqueue_assets(string $hook): void
    {
        if (strpos($hook, 'fc-') === false) {
            return;
        }

        wp_enqueue_style(
            'fc-admin-style',
            FC_PLUGIN_URL . 'assets/css/admin.css',
            [],
            FC_PLUGIN_VERSION
        );
    }

    public static function render_dashboard_page(): void
    {
        if (!current_user_can('manage_options')) {
            return;
        }

        $metrics = FC_Api_Client::fetch_metrics(30);
        $metricsError = is_wp_error($metrics) ? $metrics : null;
        $total = 0;
        $withMatch = 0;
        $withoutMatch = 0;

        if (!$metricsError && is_array($metrics)) {
            $total = isset($metrics['total']) ? (int) $metrics['total'] : 0;
            $withMatch = isset($metrics['with_match']) ? (int) $metrics['with_match'] : 0;
            $withoutMatch = isset($metrics['without_match']) ? (int) $metrics['without_match'] : 0;
        }

        $recentTable = FC_Shortcodes::render_submissions_table(['limit' => '10']);
        ?>
        <div class="wrap fc-wrap">
            <h1>FiltroClientes Dashboard</h1>
            <p><small>Build 2.0.5 (token-scope-fix)</small></p>
            <?php if ($metricsError) : ?>
                <div class="notice notice-error"><p><?php echo esc_html('Error leyendo API: ' . $metricsError->get_error_message()); ?></p></div>
            <?php endif; ?>
            <?php self::render_notice(); ?>
            <div class="fc-cards">
                <div class="fc-card">
                    <span class="fc-label">Registros Totales</span>
                    <strong class="fc-value"><?php echo esc_html((string) $total); ?></strong>
                </div>
                <div class="fc-card">
                    <span class="fc-label">Con Match</span>
                    <strong class="fc-value"><?php echo esc_html((string) $withMatch); ?></strong>
                </div>
                <div class="fc-card">
                    <span class="fc-label">Sin Match</span>
                    <strong class="fc-value"><?php echo esc_html((string) $withoutMatch); ?></strong>
                </div>
            </div>
            <div class="fc-panel">
                <h2>Datos en vivo</h2>
                <p>Este panel lee directamente desde la API en cada carga. No usa registros locales.</p>
            </div>
            <div class="fc-panel">
                <h2>Registros recientes</h2>
                <?php
                // Trusted HTML generated by our own shortcode renderer.
                echo $recentTable; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
                ?>
            </div>
        </div>
        <?php
    }

    public static function render_settings_page(): void
    {
        if (!current_user_can('manage_options')) {
            return;
        }

        $settings = FC_Settings::get();
        ?>
        <div class="wrap fc-wrap">
            <h1>Conexion API</h1>
            <p><small>Build 2.0.5 (token-scope-fix)</small></p>
            <?php self::render_notice(); ?>
            <div class="fc-panel">
                <form method="post" action="options.php">
                    <?php settings_fields('fc_api_group'); ?>
                    <table class="form-table" role="presentation">
                        <tr>
                            <th scope="row"><label for="fc_base_url">Base URL</label></th>
                            <td><input id="fc_base_url" name="<?php echo esc_attr(FC_Settings::OPTION_KEY); ?>[base_url]" type="url" class="regular-text" value="<?php echo esc_attr($settings['base_url']); ?>" placeholder="https://apiclientes.guiaysalud.com"></td>
                        </tr>
                        <tr>
                            <th scope="row"><label for="fc_client_id">Client ID</label></th>
                            <td><input id="fc_client_id" name="<?php echo esc_attr(FC_Settings::OPTION_KEY); ?>[client_id]" type="text" class="regular-text" value="<?php echo esc_attr($settings['client_id']); ?>"></td>
                        </tr>
                        <tr>
                            <th scope="row"><label for="fc_client_secret">Client Secret</label></th>
                            <td><input id="fc_client_secret" name="<?php echo esc_attr(FC_Settings::OPTION_KEY); ?>[client_secret]" type="password" class="regular-text" value="<?php echo esc_attr($settings['client_secret']); ?>" autocomplete="new-password"></td>
                        </tr>
                        <tr>
                            <th scope="row"><label for="fc_default_limit">Limite pagina</label></th>
                            <td><input id="fc_default_limit" name="<?php echo esc_attr(FC_Settings::OPTION_KEY); ?>[default_limit]" type="number" min="1" max="200" class="small-text" value="<?php echo esc_attr((string) $settings['default_limit']); ?>"></td>
                        </tr>
                    </table>
                    <?php submit_button('Guardar configuracion'); ?>
                </form>
            </div>
            <div class="fc-panel">
                <h2>Limpiar credenciales locales</h2>
                <p>Borra credenciales y token cacheado en WordPress. No borra registros en la API.</p>
                <form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>" onsubmit="return confirm('Se borraran las credenciales guardadas en WordPress. ¿Continuar?');">
                    <input type="hidden" name="action" value="fc_clear_credentials">
                    <?php wp_nonce_field('fc_clear_credentials'); ?>
                    <?php submit_button('Borrar credenciales de WP', 'secondary', 'submit', false); ?>
                </form>
            </div>
        </div>
        <?php
    }

    public static function render_record_page(): void
    {
        if (!current_user_can('manage_options')) {
            return;
        }

        $externalId = isset($_GET['external_id']) ? sanitize_text_field(wp_unslash((string) $_GET['external_id'])) : '';
        if ($externalId === '') {
            echo '<div class="wrap"><h1>Ficha clinica</h1><div class="notice notice-error"><p>Falta external_id.</p></div></div>';
            return;
        }

        $item = FC_Api_Client::fetch_submission_by_id($externalId, 20, 200);
        if (is_wp_error($item)) {
            echo '<div class="wrap"><h1>Ficha clinica</h1><div class="notice notice-error"><p>' . esc_html($item->get_error_message()) . '</p></div></div>';
            return;
        }

        $normalized = FC_Shortcodes::normalize_for_display(isset($item['normalized']) && is_array($item['normalized']) ? $item['normalized'] : []);
        $rawPayload = FC_Shortcodes::normalize_for_display(isset($item['rawPayload']) && is_array($item['rawPayload']) ? $item['rawPayload'] : []);
        $matchPayload = FC_Shortcodes::normalize_for_display(isset($item['match']) && is_array($item['match']) ? $item['match'] : []);
        $companyCodes = FC_Shortcodes::normalize_for_display(isset($item['companyCodes']) && is_array($item['companyCodes']) ? $item['companyCodes'] : []);
        $source = FC_Shortcodes::normalize_string(isset($item['source']) ? (string) $item['source'] : '');
        $createdAt = FC_Shortcodes::normalize_string(isset($item['createdAt']) ? (string) $item['createdAt'] : '');
        $backUrl = admin_url('admin.php?page=fc-dashboard');
        ?>
        <div class="wrap fc-wrap fc-record">
            <h1>Ficha clinica del paciente</h1>
            <p><a class="button" href="<?php echo esc_url($backUrl); ?>">Volver al dashboard</a></p>

            <div class="fc-record-grid">
                <div class="fc-record-card">
                    <h2>Resumen</h2>
                    <ul>
                        <li><strong>Fecha registro:</strong> <?php echo esc_html((string) ($normalized['entry_date'] ?? $createdAt)); ?></li>
                        <li><strong>Paciente:</strong> <?php echo esc_html((string) ($normalized['contacto_nombre'] ?? '')); ?></li>
                        <li><strong>Email:</strong> <?php echo esc_html((string) ($normalized['contacto_email'] ?? '')); ?></li>
                        <li><strong>Telefono:</strong> <?php echo esc_html((string) ($normalized['contacto_telefono'] ?? '')); ?></li>
                        <li><strong>Centro(s):</strong> <?php echo esc_html(FC_Shortcodes::value_to_string($normalized['centro'] ?? [])); ?></li>
                    </ul>
                </div>

                <div class="fc-record-card">
                    <h2>Datos clinicos</h2>
                    <ul>
                        <li><strong>Enfermedad:</strong> <?php echo esc_html((string) ($normalized['enfermedad'] ?? '')); ?></li>
                        <li><strong>Tipo:</strong> <?php echo esc_html((string) ($normalized['tipo_enfermedad'] ?? '')); ?></li>
                        <li><strong>Subtipo:</strong> <?php echo esc_html((string) ($normalized['subtipo_enfermedad'] ?? '')); ?></li>
                        <li><strong>Metastasis:</strong> <?php echo esc_html((string) ($normalized['metastasis'] ?? '')); ?></li>
                        <li><strong>ECOG:</strong> <?php echo esc_html((string) ($matchPayload['ecog_score'] ?? '')); ?></li>
                        <li><strong>Matches:</strong> <?php echo esc_html((string) ($matchPayload['total_matches'] ?? 0)); ?></li>
                    </ul>
                </div>
            </div>

            <div class="fc-record-card">
                <h2>Tratamiento y cirugia</h2>
                <ul>
                    <li><strong>Cirugia:</strong> <?php echo esc_html((string) ($normalized['cirugia'] ?? '')); ?></li>
                    <li><strong>Fecha cirugia:</strong> <?php echo esc_html((string) ($normalized['cirugia_fecha'] ?? '')); ?></li>
                    <li><strong>Descripcion cirugia:</strong> <?php echo esc_html((string) ($normalized['cirugia_descripcion'] ?? '')); ?></li>
                    <li><strong>Tratamiento:</strong> <?php echo esc_html((string) ($normalized['tratamiento'] ?? '')); ?></li>
                    <li><strong>Tipo de tratamiento:</strong> <?php echo esc_html(FC_Shortcodes::value_to_string($normalized['tratamiento_tipo'] ?? [])); ?></li>
                </ul>
            </div>

            <div class="fc-record-card">
                <h2>Contexto y trazabilidad</h2>
                <ul>
                    <li><strong>External ID:</strong> <?php echo esc_html($externalId); ?></li>
                    <li><strong>Source:</strong> <?php echo esc_html($source); ?></li>
                    <li><strong>Company Codes:</strong> <?php echo esc_html(FC_Shortcodes::value_to_string($companyCodes)); ?></li>
                    <li><strong>Creado API:</strong> <?php echo esc_html($createdAt); ?></li>
                    <li><strong>User ref:</strong> <?php echo esc_html((string) ($normalized['user_ref'] ?? '')); ?></li>
                </ul>
            </div>

            <div class="fc-record-card">
                <h2>JSON completo</h2>
                <h3>Normalized</h3>
                <pre><?php echo esc_html(wp_json_encode($normalized, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE)); ?></pre>
                <h3>Match</h3>
                <pre><?php echo esc_html(wp_json_encode($matchPayload, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE)); ?></pre>
                <h3>Raw payload</h3>
                <pre><?php echo esc_html(wp_json_encode($rawPayload, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE)); ?></pre>
            </div>
        </div>
        <?php
    }

    public static function handle_clear_credentials(): void
    {
        if (!current_user_can('manage_options')) {
            wp_die('No autorizado');
        }

        check_admin_referer('fc_clear_credentials');

        delete_option(FC_Settings::OPTION_KEY);
        delete_transient(FC_Settings::TOKEN_TRANSIENT);
        delete_transient(FC_Settings::TOKEN_TRANSIENT . '_read');
        delete_transient(FC_Settings::TOKEN_TRANSIENT . '_write');

        $redirect = add_query_arg(
            [
                'page' => 'fc-settings',
                'fc_notice' => 'ok',
                'fc_message' => rawurlencode('Credenciales locales eliminadas')
            ],
            admin_url('admin.php')
        );

        wp_safe_redirect($redirect);
        exit;
    }

    private static function render_notice(): void
    {
        if (!isset($_GET['fc_notice'])) {
            return;
        }

        $isError = (string) $_GET['fc_notice'] === 'error';
        $message = isset($_GET['fc_message'])
            ? sanitize_text_field(wp_unslash((string) $_GET['fc_message']))
            : ($isError ? 'Operacion con error' : 'Proceso completado');

        $class = $isError ? 'notice notice-error' : 'notice notice-success';
        printf('<div class="%s"><p>%s</p></div>', esc_attr($class), esc_html($message));
    }
}
